// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title ArcPaymaster
 * @notice Autonomous AI Fiscal Agent & Paymaster Contract on Circle's Arc Mainnet (Chain ID 5042).
 * @dev Gas is paid natively in USDC on Arc Mainnet, and all values are in native USDC.
 *      Enforces EIP-712 cryptographic proofs generated by the Gemini Agent Oracle.
 */
contract ArcPaymaster is EIP712, Ownable, ReentrancyGuard {
    using ECDSA for bytes32;

    // --- TypeHashes for EIP-712 ---
    bytes32 public constant INVOICE_VERDICT_TYPEHASH = keccak256(
        "InvoiceVerdict(bytes32 invoiceId,address recipient,uint256 amount,uint8 riskScore,uint256 nonce,uint256 deadline,string vendorName)"
    );

    struct InvoiceVerdict {
        bytes32 invoiceId;       // keccak256 hash of original document / line items
        address payable recipient; // Verified contractor/supplier EVM address
        uint256 amount;          // Amount in USDC (wei or 18 decimals)
        uint8 riskScore;         // 0 (Safest) to 100 (Critical Fraud)
        uint256 nonce;           // Replay protection nonce
        uint256 deadline;        // Signature expiration timestamp
        string vendorName;       // Human-readable vendor name
    }

    // --- State Variables ---
    address public geminiAgentOracle;  // Public key of the Gemini Autonomous Agent
    address public treasuryOfficer;    // Human supervisor key for multi-sig high-value overrides
    
    uint256 public maxAutonomousLimit; // Max USDC amount the AI can disburse without human co-signature (e.g., 500 USDC)
    uint8 public maxAllowedRiskScore;   // Highest risk score the AI is allowed to approve (e.g., 40/100)
    
    uint256 public dailyBudget;        // Maximum total spending permitted in a 24-hour cycle
    uint256 public dailySpent;         // Amount spent in the current cycle
    uint256 public currentDayIndex;    // Day index for rolling reset (block.timestamp / 1 days)

    // Tracks processed invoices to prevent double-spending & replay attacks
    mapping(bytes32 => bool) public isSettled;
    // Known fraudulent / malicious addresses flagged by Gemini Sentinel
    mapping(address => bool) public isBlacklisted;
    // Nonce tracking per recipient
    mapping(address => uint256) public nonces;

    // --- Events ---
    event InvoiceSettled(
        bytes32 indexed invoiceId,
        address indexed recipient,
        uint256 amount,
        uint8 riskScore,
        string vendorName,
        bool wasDualApproved,
        uint256 timestamp
    );

    event InvoiceQuarantined(
        bytes32 indexed invoiceId,
        address indexed recipient,
        uint8 riskScore,
        string reason,
        uint256 timestamp
    );

    event AddressBlacklisted(address indexed maliciousAccount, string reason);
    event PolicyUpdated(uint256 newAutonomousLimit, uint8 newRiskMax, uint256 newDailyBudget);
    event OracleUpdated(address indexed newAgentOracle, address indexed newOfficer);
    event TreasuryFunded(address indexed sender, uint256 amount);
    event FundsWithdrawn(address indexed recipient, uint256 amount);

    // --- Modifiers ---
    modifier onlyValidDeadline(uint256 deadline) {
        require(block.timestamp <= deadline, "ArcPaymaster: Verdict signature expired");
        _;
    }

    constructor(
        address _geminiAgentOracle,
        address _treasuryOfficer,
        uint256 _maxAutonomousLimit,
        uint8 _maxAllowedRiskScore,
        uint256 _dailyBudget
    ) EIP712("ArcPaymaster", "1.0.0") Ownable(msg.sender) {
        require(_geminiAgentOracle != address(0), "Invalid oracle address");
        require(_treasuryOfficer != address(0), "Invalid officer address");

        geminiAgentOracle = _geminiAgentOracle;
        treasuryOfficer = _treasuryOfficer;
        maxAutonomousLimit = _maxAutonomousLimit;
        maxAllowedRiskScore = _maxAllowedRiskScore;
        dailyBudget = _dailyBudget;
        currentDayIndex = block.timestamp / 1 days;
    }

    // Allows depositing native USDC directly into the treasury contract
    receive() external payable {
        emit TreasuryFunded(msg.sender, msg.value);
    }

    function fundTreasury() external payable {
        require(msg.value > 0, "ArcPaymaster: Zero deposit");
        emit TreasuryFunded(msg.sender, msg.value);
    }

    /**
     * @notice Autonomous Execution of low-risk invoices by the Gemini Agent.
     * @param verdict Structured verdict extracted by Gemini from the multimodal invoice.
     * @param agentSignature ECDSA signature from the Gemini Agent Oracle over the EIP-712 struct.
     */
    function settleInvoiceAutonomous(
        InvoiceVerdict calldata verdict,
        bytes calldata agentSignature
    ) external nonReentrant onlyValidDeadline(verdict.deadline) {
        // 1. Guardrail: Double-spend check
        require(!isSettled[verdict.invoiceId], "ArcPaymaster: Invoice already settled");
        // 2. Guardrail: Blacklist check
        require(!isBlacklisted[verdict.recipient], "ArcPaymaster: Recipient is blacklisted");
        // 3. Guardrail: Single payment autonomous cap
        require(verdict.amount <= maxAutonomousLimit, "ArcPaymaster: Exceeds autonomous limit; requires dual-approval");
        // 4. Guardrail: Risk score threshold
        require(verdict.riskScore <= maxAllowedRiskScore, "ArcPaymaster: Risk score too high");
        // 5. Guardrail: Nonce verification
        require(verdict.nonce == nonces[verdict.recipient], "ArcPaymaster: Invalid nonce");

        // 6. Verify EIP-712 cryptographic signature from Gemini Agent Oracle
        bytes32 structHash = keccak256(
            abi.encode(
                INVOICE_VERDICT_TYPEHASH,
                verdict.invoiceId,
                verdict.recipient,
                verdict.amount,
                verdict.riskScore,
                verdict.nonce,
                verdict.deadline,
                keccak256(bytes(verdict.vendorName))
            )
        );
        bytes32 digest = _hashTypedDataV4(structHash);
        address recoveredSigner = ECDSA.recover(digest, agentSignature);
        require(recoveredSigner == geminiAgentOracle, "ArcPaymaster: Unauthorized AI Agent signature");

        // 7. Enforce Daily Spending Budget
        _checkAndApplyBudget(verdict.amount);

        // 8. Update State
        isSettled[verdict.invoiceId] = true;
        nonces[verdict.recipient]++;

        // 9. Execute Native USDC Transfer on Arc
        require(address(this).balance >= verdict.amount, "ArcPaymaster: Insufficient treasury balance");
        (bool success, ) = verdict.recipient.call{value: verdict.amount}("");
        require(success, "ArcPaymaster: Native USDC transfer failed");

        emit InvoiceSettled(
            verdict.invoiceId,
            verdict.recipient,
            verdict.amount,
            verdict.riskScore,
            verdict.vendorName,
            false,
            block.timestamp
        );
    }

    /**
     * @notice High-Value Invoice Settlement requiring dual approval (Gemini AI + Human Treasury Officer).
     */
    function settleInvoiceDualApproval(
        InvoiceVerdict calldata verdict,
        bytes calldata agentSignature,
        bytes calldata officerSignature
    ) external nonReentrant onlyValidDeadline(verdict.deadline) {
        require(!isSettled[verdict.invoiceId], "ArcPaymaster: Invoice already settled");
        require(!isBlacklisted[verdict.recipient], "ArcPaymaster: Recipient is blacklisted");
        require(verdict.riskScore <= maxAllowedRiskScore, "ArcPaymaster: Risk score too high");
        require(verdict.nonce == nonces[verdict.recipient], "ArcPaymaster: Invalid nonce");

        bytes32 structHash = keccak256(
            abi.encode(
                INVOICE_VERDICT_TYPEHASH,
                verdict.invoiceId,
                verdict.recipient,
                verdict.amount,
                verdict.riskScore,
                verdict.nonce,
                verdict.deadline,
                keccak256(bytes(verdict.vendorName))
            )
        );
        bytes32 digest = _hashTypedDataV4(structHash);

        // Verify both AI Oracle and Human Supervisor
        address recoveredAgent = ECDSA.recover(digest, agentSignature);
        address recoveredOfficer = ECDSA.recover(digest, officerSignature);
        require(recoveredAgent == geminiAgentOracle, "ArcPaymaster: Invalid AI Agent signature");
        require(recoveredOfficer == treasuryOfficer, "ArcPaymaster: Invalid Officer signature");

        _checkAndApplyBudget(verdict.amount);

        isSettled[verdict.invoiceId] = true;
        nonces[verdict.recipient]++;

        require(address(this).balance >= verdict.amount, "ArcPaymaster: Insufficient treasury balance");
        (bool success, ) = verdict.recipient.call{value: verdict.amount}("");
        require(success, "ArcPaymaster: Native USDC transfer failed");

        emit InvoiceSettled(
            verdict.invoiceId,
            verdict.recipient,
            verdict.amount,
            verdict.riskScore,
            verdict.vendorName,
            true,
            block.timestamp
        );
    }

    /**
     * @notice Records an on-chain threat quarantine and auto-blacklists scammer addresses.
     */
    function quarantineFraudulentInvoice(
        bytes32 invoiceId,
        address scammerAddress,
        uint8 riskScore,
        string calldata reason,
        bool autoBlacklist
    ) external {
        require(msg.sender == geminiAgentOracle || msg.sender == owner(), "Unauthorized");
        
        if (autoBlacklist && scammerAddress != address(0)) {
            isBlacklisted[scammerAddress] = true;
            emit AddressBlacklisted(scammerAddress, reason);
        }

        emit InvoiceQuarantined(invoiceId, scammerAddress, riskScore, reason, block.timestamp);
    }

    /**
     * @dev Internal check to handle rolling 24-hour daily budget caps.
     */
    function _checkAndApplyBudget(uint256 amount) internal {
        uint256 todayIndex = block.timestamp / 1 days;
        if (todayIndex > currentDayIndex) {
            currentDayIndex = todayIndex;
            dailySpent = 0;
        }

        require(dailySpent + amount <= dailyBudget, "ArcPaymaster: Daily treasury budget cap exceeded");
        dailySpent += amount;
    }

    // --- Admin Governance ---
    function updatePolicy(
        uint256 newAutonomousLimit,
        uint8 newMaxRiskScore,
        uint256 newDailyBudget
    ) external onlyOwner {
        maxAutonomousLimit = newAutonomousLimit;
        maxAllowedRiskScore = newMaxRiskScore;
        dailyBudget = newDailyBudget;
        emit PolicyUpdated(newAutonomousLimit, newMaxRiskScore, newDailyBudget);
    }

    function updateAuthorities(address newAgentOracle, address newOfficer) external onlyOwner {
        require(newAgentOracle != address(0) && newOfficer != address(0), "Zero address");
        geminiAgentOracle = newAgentOracle;
        treasuryOfficer = newOfficer;
        emit OracleUpdated(newAgentOracle, newOfficer);
    }

    function setBlacklist(address target, bool blacklisted, string calldata reason) external onlyOwner {
        isBlacklisted[target] = blacklisted;
        if (blacklisted) {
            emit AddressBlacklisted(target, reason);
        }
    }

    function emergencyWithdraw(uint256 amount, address payable recipient) external onlyOwner nonReentrant {
        require(recipient != address(0), "Zero address");
        require(amount <= address(this).balance, "Insufficient balance");
        (bool success, ) = recipient.call{value: amount}("");
        require(success, "Transfer failed");
        emit FundsWithdrawn(recipient, amount);
    }

    function getTreasuryBalance() external view returns (uint256) {
        return address(this).balance;
    }
}
