// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

/**
 * @title ArcPaymaster
 * @notice Enterprise Autonomous AI Fiscal Officer & Escrow on Circle's Arc Mainnet.
 * @dev Supports both Native USDC gas/transfers on Arc (Chain ID 5042) and ERC-20 USDC.
 *      Enforces EIP-712 cryptographic proofs generated by the Gemini Agent Oracle.
 */
contract ArcPaymaster is EIP712, Ownable, ReentrancyGuard {
    using ECDSA for bytes32;
    using SafeERC20 for IERC20;

    // --- EIP-712 TypeHash ---
    bytes32 public constant INVOICE_VERDICT_TYPEHASH = keccak256(
        "InvoiceVerdict(bytes32 invoiceId,address recipient,uint256 amount,uint8 riskScore,uint256 nonce,uint256 deadline,string vendorName)"
    );

    struct InvoiceVerdict {
        bytes32 invoiceId;         // keccak256 hash of original document / line items
        address payable recipient; // Verified supplier/contractor EVM address
        uint256 amount;            // Amount in USDC (native or 6/18 decimals)
        uint8 riskScore;           // 0 (Safe) to 100 (Critical Fraud)
        uint256 nonce;             // Sequential nonce per recipient
        uint256 deadline;          // Signature expiration timestamp
        string vendorName;         // Vendor name for on-chain indexing
    }

    // --- State Variables ---
    address public geminiAgentOracle;  // Public key of the Gemini AI Agent Oracle
    address public treasuryOfficer;    // Human multi-sig / supervisor key
    address public usdcTokenAddress;   // Optional ERC-20 USDC token address (if address(0), uses native Arc USDC)

    uint256 public maxAutonomousLimit; // Max USDC the AI can disburse autonomously (e.g. 500 USDC)
    uint8 public maxAllowedRiskScore;   // Highest risk score the AI is allowed to approve (e.g. 40/100)

    uint256 public dailyBudget;        // Maximum allowed spending per rolling 24h cycle
    uint256 public dailySpent;         // Amount spent in the current cycle
    uint256 public currentDayIndex;    // Day index (block.timestamp / 1 days)

    // Tracks processed invoices to prevent replay attacks
    mapping(bytes32 => bool) public isSettled;
    // Known fraudulent / malicious addresses quarantined by Gemini Sentinel
    mapping(address => bool) public isBlacklisted;
    // Nonce tracking per recipient for cryptographic order and replay defense
    mapping(address => uint256) public nonces;

    // --- Events ---
    event InvoiceSettled(
        bytes32 indexed invoiceId,
        address indexed recipient,
        uint256 amount,
        uint8 riskScore,
        string vendorName,
        bool wasDualApproved,
        uint256 timestamp
    );

    event InvoiceQuarantined(
        bytes32 indexed invoiceId,
        address indexed recipient,
        uint8 riskScore,
        string reason,
        uint256 timestamp
    );

    event AddressBlacklisted(address indexed maliciousAccount, string reason);
    event PolicyUpdated(uint256 newAutonomousLimit, uint8 newRiskMax, uint256 newDailyBudget);
    event OracleUpdated(address indexed newAgentOracle, address indexed newOfficer);
    event UsdcTokenConfigured(address indexed token);
    event TreasuryFunded(address indexed sender, uint256 amount);
    event FundsWithdrawn(address indexed recipient, uint256 amount);

    // --- Modifiers ---
    modifier onlyValidDeadline(uint256 deadline) {
        require(block.timestamp <= deadline, "ArcPaymaster: Verdict signature expired");
        _;
    }

    constructor(
        address _geminiAgentOracle,
        address _treasuryOfficer,
        address _usdcTokenAddress,
        uint256 _maxAutonomousLimit,
        uint8 _maxAllowedRiskScore,
        uint256 _dailyBudget
    ) EIP712("ArcPaymaster", "1.0.0") Ownable(msg.sender) {
        require(_geminiAgentOracle != address(0), "Invalid oracle address");
        require(_treasuryOfficer != address(0), "Invalid officer address");

        geminiAgentOracle = _geminiAgentOracle;
        treasuryOfficer = _treasuryOfficer;
        usdcTokenAddress = _usdcTokenAddress;
        maxAutonomousLimit = _maxAutonomousLimit;
        maxAllowedRiskScore = _maxAllowedRiskScore;
        dailyBudget = _dailyBudget;
        currentDayIndex = block.timestamp / 1 days;
    }

    // Accept native USDC deposits on Circle Arc
    receive() external payable {
        emit TreasuryFunded(msg.sender, msg.value);
    }

    function fundTreasury() external payable {
        require(msg.value > 0, "ArcPaymaster: Zero deposit");
        emit TreasuryFunded(msg.sender, msg.value);
    }

    /**
     * @notice Returns the current nonce for a recipient to construct EIP-712 payloads.
     */
    function getNonce(address recipient) external view returns (uint256) {
        return nonces[recipient];
    }

    /**
     * @notice Autonomous Execution of low-risk invoices by the Gemini Agent.
     */
    function settleInvoiceAutonomous(
        InvoiceVerdict calldata verdict,
        bytes calldata agentSignature
    ) external nonReentrant onlyValidDeadline(verdict.deadline) {
        // 1. Double-spend protection
        require(!isSettled[verdict.invoiceId], "ArcPaymaster: Invoice already settled");
        // 2. Blacklist check
        require(!isBlacklisted[verdict.recipient], "ArcPaymaster: Recipient is blacklisted");
        // 3. Autonomous spending limit check
        require(verdict.amount <= maxAutonomousLimit, "ArcPaymaster: Exceeds autonomous limit; requires dual-approval");
        // 4. Risk score threshold
        require(verdict.riskScore <= maxAllowedRiskScore, "ArcPaymaster: Risk score too high");
        // 5. Dynamic nonce validation
        require(verdict.nonce == nonces[verdict.recipient], "ArcPaymaster: Invalid nonce");

        // 6. Verify EIP-712 signature from authorized Gemini Oracle
        bytes32 structHash = keccak256(
            abi.encode(
                INVOICE_VERDICT_TYPEHASH,
                verdict.invoiceId,
                verdict.recipient,
                verdict.amount,
                verdict.riskScore,
                verdict.nonce,
                verdict.deadline,
                keccak256(bytes(verdict.vendorName))
            )
        );
        bytes32 digest = _hashTypedDataV4(structHash);
        address recoveredSigner = ECDSA.recover(digest, agentSignature);
        require(recoveredSigner == geminiAgentOracle, "ArcPaymaster: Unauthorized AI Agent signature");

        // 7. Enforce Daily Spending Budget
        _checkAndApplyBudget(verdict.amount);

        // 8. State updates
        isSettled[verdict.invoiceId] = true;
        nonces[verdict.recipient]++;

        // 9. Dual-mode transfer: Native USDC (Arc Layer 1) or ERC-20 USDC
        _transferFunds(verdict.recipient, verdict.amount);

        emit InvoiceSettled(
            verdict.invoiceId,
            verdict.recipient,
            verdict.amount,
            verdict.riskScore,
            verdict.vendorName,
            false,
            block.timestamp
        );
    }

    /**
     * @notice High-Value Invoice Settlement requiring dual approval (AI Oracle + Treasury Officer).
     */
    function settleInvoiceDualApproval(
        InvoiceVerdict calldata verdict,
        bytes calldata agentSignature,
        bytes calldata officerSignature
    ) external nonReentrant onlyValidDeadline(verdict.deadline) {
        require(!isSettled[verdict.invoiceId], "ArcPaymaster: Invoice already settled");
        require(!isBlacklisted[verdict.recipient], "ArcPaymaster: Recipient is blacklisted");
        require(verdict.riskScore <= maxAllowedRiskScore, "ArcPaymaster: Risk score too high");
        require(verdict.nonce == nonces[verdict.recipient], "ArcPaymaster: Invalid nonce");

        bytes32 structHash = keccak256(
            abi.encode(
                INVOICE_VERDICT_TYPEHASH,
                verdict.invoiceId,
                verdict.recipient,
                verdict.amount,
                verdict.riskScore,
                verdict.nonce,
                verdict.deadline,
                keccak256(bytes(verdict.vendorName))
            )
        );
        bytes32 digest = _hashTypedDataV4(structHash);

        address recoveredAgent = ECDSA.recover(digest, agentSignature);
        address recoveredOfficer = ECDSA.recover(digest, officerSignature);
        require(recoveredAgent == geminiAgentOracle, "ArcPaymaster: Invalid AI Agent signature");
        require(recoveredOfficer == treasuryOfficer, "ArcPaymaster: Invalid Officer signature");

        _checkAndApplyBudget(verdict.amount);

        isSettled[verdict.invoiceId] = true;
        nonces[verdict.recipient]++;

        _transferFunds(verdict.recipient, verdict.amount);

        emit InvoiceSettled(
            verdict.invoiceId,
            verdict.recipient,
            verdict.amount,
            verdict.riskScore,
            verdict.vendorName,
            true,
            block.timestamp
        );
    }

    /**
     * @notice Quarantines an invoice and blacklists malicious actors.
     */
    function quarantineFraudulentInvoice(
        bytes32 invoiceId,
        address scammerAddress,
        uint8 riskScore,
        string calldata reason,
        bool autoBlacklist
    ) external {
        require(msg.sender == geminiAgentOracle || msg.sender == owner(), "Unauthorized");

        if (autoBlacklist && scammerAddress != address(0)) {
            isBlacklisted[scammerAddress] = true;
            emit AddressBlacklisted(scammerAddress, reason);
        }

        emit InvoiceQuarantined(invoiceId, scammerAddress, riskScore, reason, block.timestamp);
    }

    /**
     * @dev Internal transfer supporting Native USDC (18 decimals) and ERC-20 USDC (standard 6 decimals or other).
     */
    function _transferFunds(address payable recipient, uint256 amount) internal {
        if (usdcTokenAddress == address(0)) {
            // Native USDC on Arc (18 decimals)
            require(address(this).balance >= amount, "ArcPaymaster: Insufficient native treasury balance");
            (bool success, ) = recipient.call{value: amount}("");
            require(success, "ArcPaymaster: Native USDC transfer failed");
        } else {
            // ERC-20 USDC: normalize 18 decimal amount to token's native decimals if 6 decimals
            uint256 transferAmount = amount;
            // Standard USDC ERC-20 uses 6 decimals. If amount passed is 18 decimals, scale down to 6:
            // 1 USDC in 18 decimals = 1e18 wei; in 6 decimals = 1e6 units
            if (transferAmount >= 1e12) {
                transferAmount = transferAmount / 1e12;
            }
            IERC20(usdcTokenAddress).safeTransfer(recipient, transferAmount);
        }
    }

    /**
     * @dev Internal check to handle rolling 24-hour daily budget caps.
     */
    function _checkAndApplyBudget(uint256 amount) internal {
        uint256 todayIndex = block.timestamp / 1 days;
        if (todayIndex > currentDayIndex) {
            currentDayIndex = todayIndex;
            dailySpent = 0;
        }

        require(dailySpent + amount <= dailyBudget, "ArcPaymaster: Daily treasury budget cap exceeded");
        dailySpent += amount;
    }

    // --- Admin Governance ---
    function updatePolicy(
        uint256 newAutonomousLimit,
        uint8 newMaxRiskScore,
        uint256 newDailyBudget
    ) external onlyOwner {
        maxAutonomousLimit = newAutonomousLimit;
        maxAllowedRiskScore = newMaxRiskScore;
        dailyBudget = newDailyBudget;
        emit PolicyUpdated(newAutonomousLimit, newMaxRiskScore, newDailyBudget);
    }

    function updateAuthorities(address newAgentOracle, address newOfficer) external onlyOwner {
        require(newAgentOracle != address(0) && newOfficer != address(0), "Zero address");
        geminiAgentOracle = newAgentOracle;
        treasuryOfficer = newOfficer;
        emit OracleUpdated(newAgentOracle, newOfficer);
    }

    function setUsdcToken(address newToken) external onlyOwner {
        usdcTokenAddress = newToken;
        emit UsdcTokenConfigured(newToken);
    }

    function setBlacklist(address target, bool blacklisted, string calldata reason) external onlyOwner {
        isBlacklisted[target] = blacklisted;
        if (blacklisted) {
            emit AddressBlacklisted(target, reason);
        }
    }

    function emergencyWithdraw(uint256 amount, address payable recipient) external onlyOwner nonReentrant {
        require(recipient != address(0), "Zero address");
        if (usdcTokenAddress == address(0)) {
            require(amount <= address(this).balance, "Insufficient balance");
            (bool success, ) = recipient.call{value: amount}("");
            require(success, "Transfer failed");
        } else {
            IERC20(usdcTokenAddress).safeTransfer(recipient, amount);
        }
        emit FundsWithdrawn(recipient, amount);
    }

    function getTreasuryBalance() external view returns (uint256) {
        if (usdcTokenAddress == address(0)) {
            return address(this).balance;
        } else {
            return IERC20(usdcTokenAddress).balanceOf(address(this));
        }
    }
}
